# Generated by Django 3.1.2 on 2021-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmp_url', models.TextField(null=True)),
                ('kmp_bg_image', models.TextField(null=True)),
                ('kmp_desc', models.TextField(null=True)),
            ],
        ),
    ]
