# Generated by Django 3.1.2 on 2021-05-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sale', models.IntegerField(null=True)),
                ('store', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=100)),
                ('id_user', models.IntegerField(null=True)),
            ],
        ),
    ]
